apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: sports-store
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: lironefitoussi/sports-store-cart-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef: { name: app-config, key: MONGO_URI }
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: app-secrets, key: JWT_SECRET }
            - name: CATALOG_URL
              valueFrom:
                configMapKeyRef: { name: app-config, key: CATALOG_URL }
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: sports-store
spec:
  selector:
    app: cart
  ports:
    - port: 8000
      targetPort: 8000
