apiVersion: v1
kind: Pod
metadata:
  name: auto-pod
  namespace: default
  labels:
    lab: manual-scheduling
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
